### ISSUE TITLE
babel-loaderのインストールについて

### ISSUE THREAD

**Issue by mildjester** [yuumi3/react_book#12]
reactを勉強しようと思い、書籍を購入させて頂きました。
とても分かりやすくて助かっています。

まだ読み途中なのですが、１点質問させてください。
npmインストールをする箇所(30ページ)で`babel-loader`を2回インストールしているのですが、
これは何か意味があるのでしょうか？

**Comment by yuumi3** [comment]
ご指摘ありがとうございます。 
意味はしません、間違いでしたので正誤表に追加しました。

ありがとうございます。
