### ISSUE TITLE
hello-reactについてwebpack4になった影響で、エラーが出てしまうようです。

### ISSUE THREAD

**Issue by tetsuroshimura** [yuumi3/react_book#13]
Error: Cannot find module 'webpack-cli/bin/config-yargs'
---
CLIはwebpack-cliという別のパッケージに移動しました。
CLIを使用するにはwebpack自体に加えて 'webpack-cli'をインストールしてください。
-npmを使用する場合：npm install webpack-cli -D
-yarnを使用する場合：yarn add webpack-cli -D
---
この部分ですかね。

**Comment by yuumi3** [comment]
webpack4のエラー報告ありがとうございます。
週末に確認して修正します。

**Comment by yuumi3** [comment]
ありがとうございます !!
インストール手順と webpack.config.js を変更しました。
