### ISSUE TITLE
200ページのテスティングについて

### ISSUE THREAD

**Issue by Kota2017** [yuumi3/react_book#15]
正誤表にある箇所を修正しても
TypeError: nightmare.goto(...).touchTap is not a function
と出て、touchTapを読み込めません。なぜでしょうか。。

**Comment by yuumi3** [comment]
Kota2017さん、Nightmareの変更でtouchTap()ヘルパーが不要になっていましたが正誤表の修正が間違っていまいした。test/index.jsをサポートページの [テスティング](/yuumi3/react_book/blob/master/sources/test.md)  のコードに変更して実行してもらえますか、お手数かけます。

**Comment by yuumi3** [comment]
時間が経ったので閉じます
