### ISSUE TITLE
最新の環境でhello_reactがコンパイルエラーになります

### ISSUE THREAD

**Issue by tomita-yoshihiko** [yuumi3/react_book#18]
![error](https://user-images.githubusercontent.com/45126133/48662824-df924a80-eaca-11e8-91da-0642799c105b.jpg)

**Comment by tomita-yoshihiko** [comment]
package.jsonのバージョンは下記の通りです

"dependencies": {
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  },
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "css-loader": "^1.0.1",
    "eslint": "^5.9.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-react": "^7.11.1",
    "style-loader": "^0.23.1",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  }

**Comment by yuumi3** [comment]
エラー報告ありがとうございます。
インストールに babel-eslint を追加し、.eslintrc.json を変更しました。

新しい [インストール手順 Windows](docs/install_win.md) で行うか、

* `npm install babel-eslint --save-dev` を実行し
* .eslintrc.json ファイルの2行目に `"parser": "babel-eslint",` を追加して下さい

**Comment by tomita-yoshihiko** [comment]
素早い対応ありがとうございます。正常動作を確認しました。
Windows10のWSL/Ubuntu環境でもmacの手順で動作しました。
