### ISSUE TITLE
6.4 PropsとState, pp. 115の記載に質問です。

### ISSUE THREAD

**Issue by externvoid** [yuumi3/react_book#2]
「scoreというパラメーターが渡って来ます。このパラメーターのことをPropsと呼びます。」
との記載があります。

「human, computer, judgmentというパラメーターが渡って来ます。」の誤りでは無いでしょうか？

**Comment by yuumi3** [comment]
externvoidさん、
その通りです。
間違いのご指摘ありがとうございます、正誤表に追加しました。
