### ISSUE TITLE
教えてください。35ページ「npm start」できません。

### ISSUE THREAD

**Issue by hidechy** [yuumi3/react_book#21]
ここに書けば著者様に届きますでしょうか。
35ページの「npm start」をしたのですが、
下記のようなエラーが出て進むことができません。
対処法など教えていただけますか。

[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {app} [built]
[./src/index.js] 2.04 KiB {app} [built] [failed] [2 errors]
    + 18 hidden modules

ERROR in ./src/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

C:\HIDEYUKI\react_book\src\index.js
  6:36  error  Parsing error: Unexpected token ;

✖ 1 problem (1 error, 0 warnings)

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\HIDEYUKI\react_book\src\index.js: Unexpected token (5:4)

  3 |
  4 | ReactDOM.render(
> 5 |     <h1>Hello World</h1> ,
    |     ^
  6 |     document.getElementById('root');
  7 | );
  8 |

**Comment by Kento75** [comment]
著者ではないですが、お答えします。

本に記載されているモジュールと現行のモジュールのバージョンが異なるため動作しないのだと思います。（主にBabelモジュール）

現行のバージョンへ差し替えたドキュメントが用意されています。

https://github.com/yuumi3/react_book/blob/master/docs/install_win.md

**Comment by hidechy** [comment]
Kento75様

教えていただいたページで解決しました。
ご親切にありがとうございました。
本当に感謝しています。

**Comment by yuumi3** [comment]
@Kento75 さん、代理回答ありがとうございます !!
