### ISSUE TITLE
5章JSXの基本 で npm start をすると eslint のエラーが表示される

### ISSUE THREAD

**Issue by gakuton** [yuumi3/react_book#25]
初めて React を学ぶためにこちらの本で学習を進めています。

標題の通り、5章のサンプルコードに沿って進めている中で、`npm start` をすると 以下のエラーが表示されます。
（5章を最後まで進めた際の表示です）

知識不足によるものかと思われますが、対処法がわからなかったのでお聞きしたいです。
よろしくお願いします。

```
ERROR in ./src/index.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/Users/gakuton/money_book/src/index.js
   6:7   error  'Moneybook' is assigned a value but never used  no-unused-vars
  29:10  error  'book.date' is missing in props validation      react/prop-types
  29:16  error  'book.item' is missing in props validation      react/prop-types
  29:22  error  'book.amount' is missing in props validation    react/prop-types
  29:38  error  'book' is missing in props validation           react/prop-types
  44:22  error  'children' is missing in props validation       react/prop-types
  51:4   error  'MoneyBook' is not defined

**Comment by yuumi3** [comment]
gakutonさん、本を買って頂ありがとうございます。

` 6:7   error  'Moneybook' is assigned a value but never used` と`51:4   error  'MoneyBook' is not defined` は
6行目の MoneyBook の Bが小文字になっているからです。
 
29行目のエラーですが、39〜41行目の MoneyBookItem.propTypes の定義に正しくないところがあるのではないかと思います
https://github.com/yuumi3/react_book/blob/master/sources/jsx.md のコードと比較してみて下さい。

**Comment by gakuton** [comment]
ご回答ありがとうございます。

ご指摘の通り、39~41行目の記述と異なる点があり、それが原因になっていました。
次回以降元のコードと入念に照らし合わせて確認しながら進めていきます。

**Comment by yuumi3** [comment]
@gakuton がんばって下さい
