### ISSUE TITLE
初めまして、フォームのソースコードがどこにあるか教えてもらえないでしょうか

### ISSUE THREAD

**Issue by amato** [yuumi3/react_book#27]
初めまして非プログラマですが、初心者でReact触ろうとしているものです。
githubの使い方もまだ不慣れでして、フォーム（p123 )の部分のソースコードがどこにあるかわからず、教えていただけないでしょうか。よろしくお願いします。

**Comment by yuumi3** [comment]
@amato 少しわかりにくいかもしれませんね。
ここにあります →  https://github.com/yuumi3/react_book/blob/master/sources/component.md#6-7-フォーム

**Comment by amato** [comment]
ありがとうございます！よく読めていませんでした、動かすことができました。
