### ISSUE TITLE
6-7-2 Uncontrolled Components pp. 131 ref属性と無名関数について質問です。

### ISSUE THREAD

**Issue by externvoid** [yuumi3/react_book#3]
「この無名関数の引数(node)には、このタグを参照するための情報が入って来ます。」と記載があり、pp.132のソースコードには、
ref={(node) => this.payingIn = node}

との記載があります。
「タグを参照する情報」とは何でしょう？それをthis.payingInに代入する操作は、どの様な意味があるのでしょうか？

ご回答頂きます様、お願い致します。

**Comment by yuumi3** [comment]
externvoidさん、

jQuery でinputタグの値を取得するには `<input id="answerText" />` のようにinputタグにID等を付け `$("#answerText").val()` のようにアクセスしますよね。

Reactでは、このようにinputタグの値をアクセスする際に、古いバージョンでは `<input ref="answerText" />`  のようにinputタグにref属性で名前(文字列)を指定し、`this.refs.answerText` のようにしてアクセス出来るようになっていました。

しかし、この方式は性能が良くない、使いにくい等の理由で `<input ref={(node) => this.answerText = node} />` のように無名関数を渡し、その無名関数でinputタグのオブジェクト(inputタグを参照するための)情報を受け取りインスタンス変数answerTextに代入しています。
このインスタンス変数answerTextを使うと ` this.answerText.value`  のようにしてinputタグの値が取得できます。

どうでしょうか？  参照する情報とは C言語のポインターのようなものなのですが・・・
判らない点があれば、質問ねがいます。

ちなみに、このようになった経過は https://reactjs.org/docs/refs-and-the-dom#legacy-api-string-refs に書かれています

**Comment by externvoid** [comment]
なるほどぉ。`this.answerText.value`の様に

**Comment by yuumi3** [comment]
まずは、おまじない的な理解でも良いと思います。ただし、いつかは原理も理解出来るようになって下さいね。
