### ISSUE TITLE
「7-1-2 じゃんけんにMaterial-UIを組み込む」

### ISSUE THREAD

**Issue by TaroHattori** [yuumi3/react_book#30]
書籍とGitHubのサンプルのコードが異なります。

書籍ではコード＜MuiThemeProvider＞、＜/MuiThemeProvider＞を挿入してMaterial-UIを使用していますが、このGitHubサイトのコードはそうなっていません。

そこで書籍の通りにコードを打ち直して走らせてみましたが、「./src/index.js Module not found: Can't resolve '@material-ui/styles/MuiThemeProvider' in '/workspaces/React-App/jyanken-app/src'」というエラーメッセージが出ました。

調べてみた結果、下記コードが正しいのではないでしょうか。
＜ThemeProvider＞
import ThemeProvider from '@material-ui/styles/ThemeProvider'

ご確認をお願い致します。

**Comment by yuumi3** [comment]
@TaroHattori さん、書籍が出版された後でMaterial-UIが大幅なバージョンアップが行われ書籍のコードは動きませんので、このGitHubサポートページのコードを使って下さい。
