### ISSUE TITLE
無名関数

### ISSUE THREAD

**Issue by arton** [yuumi3/react_book#8]
P.82の「このように、無名関数は……」にひっかりを覚えました。
functionキーワードを使って有名関数を定義しても、その場では実行されず、名前を指定して他の関数へ渡せますよね。したがって無名関数の特徴の説明にはなっていないと思います。
他の関数へ与える位置(引数の指定)と関数の定義が一致する事が最大の特徴(というよりもメリット)ではないでしょうか。

**Comment by yuumi3** [comment]
ご指摘ありがとうございます。遅延評価構文的な事を言いたかったのですが説明が上手くないですね。

**Comment by yuumi3** [comment]
もし第2版を出す機会があれば説明を再検討します。
