### ISSUE TITLE
react-router-domについては問題があります。

### ISSUE THREAD

**Issue by ttson24** [yuumi3/react_book#9]
すみません。
私はあなたの本を読みました。以下の問題があります。
index.jsファイルに：
```
import React from 'react';
import ReactDom from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';
import ReduxPromise from 'redux-promise';
import { BrowserRouter as Router, Route} from 'react-router-dom'

const createStoreWithMiddleware = applyMiddleware(ReduxPromise)(createStore);

ReactDom.render(
  <Provider store={createStoreWithMiddleware(reducers)}>
    <Router>
      <Route path='/' component={App}>
        <Route path='/weather' component={WeatherList} />
      </Route>
    </Router>
  </Provider>
  ,document.querySelector('#react-container')
);
```
app.js ファイルに：
```
export default class App extends Component {

  render(){
    return (
      <div className="container col-md-12">
        <SearchBar/>
        {this.props.children};
// ここに内容サイトを表示されたいです。
      </div>
    )
  }
}
```
しかし、プロジェクトを実行する時にエラーを表示されます。
`browser.js:49 Warning: You should not use <Route component> and <Route children> in the same route; <Route children> will be ignored`
色々段階を調べていますが、答え処理はまだ知りません。教えていたでけませんか。
宜しくお願い致します。

  全部ソースは以下のリンクにおいています。
https://github.com/ttson24/react_children/tree/master

**Comment by yuumi3** [comment]
Reduxを使うと全ての state は Reduxで管理しますよね、その場合は https://github.com/reactjs/react-router-redux のような Redux に対応した Routerを使う必要があります。

https://github.com/reactjs/react-router-redux のページの Examples で使い方を勉強して下さい。
